// Importing the CSS file generated by Tailwind/PostCSS (or any custom App styles).
// Tailwind injects utility classes through this file after build.
import "./App.css";

// React Functional Component: App
// This is the main component of your React app.
// React components return JSX (HTML-like syntax inside JavaScript).
function App() {
  return (
    <>
      {/*
        ------------------------
        1. INLINE CSS WITH FLEX
        ------------------------
        - Here, we are using inline CSS styles directly inside the JSX `style={{}}` attribute.
        - `display: "flex"` makes the parent <div> a Flexbox container.
        - `justify-content: "space-between"` ensures that the child elements are placed
          at equal distances, with maximum space between them.
        - Each child <div> has its own background color for distinction.
      */}
      <div style={{ display: "flex", justifyContent: "space-between" }}>
        <div style={{ backgroundColor: "red" }}>
          Hi, Hello my name is Yaswanth
        </div>
        <div style={{ backgroundColor: "green" }}>
          Hi, Hello my name is Yaswanth
        </div>
        <div style={{ backgroundColor: "blue" }}>
          Hi, Hello my name is Yaswanth
        </div>
      </div>

      {/*
        ------------------------
        2. USING TAILWIND CSS
        ------------------------
        - Instead of writing inline CSS manually, we use Tailwind CSS utility classes.
        - Tailwind provides single-purpose utility classes that map directly to CSS properties.
        - `flex` → makes the container a flexbox (like display: flex).
        - `justify-center` → centers the child elements horizontally inside the flex container.
        - `bg-red-500`, `bg-green-500` → predefined Tailwind color classes with different shades.
        - Notice: For the third child, we are mixing inline CSS (blue background) with Tailwind.
      */}
      <div className="flex justify-center">
        <div className="bg-red-500">Hi, Hello my name is Yaswanth</div>
        <div className="bg-green-500">Hi, Hello my name is Yaswanth</div>
        <div style={{ backgroundColor: "blue" }}>
          Hi, Hello my name is Yaswanth
        </div>
      </div>
    </>
  );
}

// Exporting App component so it can be imported and rendered by `main.jsx` or `index.jsx`.
export default App;

/* 
  ------------------------
  3. TAILWIND CSS SETUP NOTES
  ------------------------
  - Tailwind CSS is a utility-first CSS framework, meaning instead of writing custom CSS rules,
    you use pre-built utility classes directly in your HTML/JSX.
  - Installation Steps:
    1. Run: npm install -D tailwindcss postcss autoprefixer
       - "-D" means these are devDependencies (only required during development, 
         not shipped into the production bundle).
    2. Run: npx tailwindcss init -p
       - This creates `tailwind.config.js` and `postcss.config.js`.
       - These config files tell your build tool (Vite, CRA, Next.js, etc.)
         how to process Tailwind and PostCSS.
    3. Add Tailwind directives into `index.css` or `App.css`:
         @tailwind base;
         @tailwind components;
         @tailwind utilities;

  ------------------------
  4. mui.com NOTE
  ------------------------
  - mui.com refers to Material UI (MUI), a popular React UI framework.
  - Unlike Tailwind (utility-first), MUI provides ready-made components 
    like Buttons, Dialogs, AppBars with built-in styles.
  - You can use Tailwind and MUI together depending on your project needs.
*/
