// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
dotenv.config();
import { defineConfig } from 'prisma/config';

const isCli = process.argv.includes('migrate') || process.argv.includes('db');

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: {
    url: isCli ? process.env.DATABASE_URL_DIRECT : process.env.DATABASE_URL,
  },
});
